SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

ALTER TABLE `europlanet_na1`.`observatories` ADD COLUMN `creation_date` DATETIME NOT NULL  AFTER `partner_observatories` , ADD COLUMN `modification_date` DATETIME NULL DEFAULT NULL  AFTER `creation_date` ;

ALTER TABLE `europlanet_na1`.`space_missions` ADD COLUMN `creation_date` DATETIME NOT NULL  AFTER `web_address` , ADD COLUMN `modification_date` DATETIME NULL DEFAULT NULL  AFTER `creation_date` ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
