SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

ALTER TABLE `europlanet_na1`.`instruments`
	CHANGE COLUMN `field_of_view` `field_of_view` TEXT NULL DEFAULT NULL  AFTER `polarisation` ;

ALTER TABLE `europlanet_na1`.`instruments` 
	ADD COLUMN `max_frames_per_sec` FLOAT NULL DEFAULT NULL  AFTER `field_of_view` , 
	ADD COLUMN `frame_size` TEXT NULL DEFAULT NULL  AFTER `max_frames_per_sec` , 
	ADD COLUMN `min_exposure_time` FLOAT NULL DEFAULT NULL  AFTER `frame_size` , 
	ADD COLUMN `max_exposure_time` FLOAT NULL DEFAULT NULL  AFTER `min_exposure_time` , 
	ADD COLUMN `color_bw_chip` TINYINT(1) NULL DEFAULT NULL  AFTER `max_exposure_time` , 
	ADD COLUMN `ccd_chip_type` TEXT NULL DEFAULT NULL  AFTER `color_bw_chip` ;
	

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
