INSERT INTO `countries` (`id`, `acronym`, `name`) VALUES
(1, 'AF', 'Afghanistan'),
(2, 'AL', 'Albania'),
(3, 'DZ', 'Algeria'),
(4, 'AS', 'American Samoa'),
(5, 'AD', 'Andorra'),
(6, 'AO', 'Angola'),
(7, 'AI', 'Anguilla'),
(8, 'AQ', 'Antarctica'),
(9, 'AG', 'Antigua And Barbuda'),
(10, 'AR', 'Argentina'),
(11, 'AM', 'Armenia'),
(12, 'AW', 'Aruba'),
(13, 'AU', 'Australia'),
(14, 'AT', 'Austria'),
(15, 'AZ', 'Azerbaijan'),
(16, 'BS', 'Bahamas'),
(17, 'BH', 'Bahrain'),
(18, 'BD', 'Bangladesh'),
(19, 'BB', 'Barbados'),
(20, 'BY', 'Belarus'),
(21, 'BE', 'Belgium'),
(22, 'BZ', 'Belize'),
(23, 'BJ', 'Benin'),
(24, 'BM', 'Bermuda'),
(25, 'BT', 'Bhutan'),
(26, 'BO', 'Bolivia'),
(27, 'BA', 'Bosnia & Herzegovina'),
(28, 'BW', 'Botswana'),
(29, 'BV', 'Bouvet Island'),
(30, 'BR', 'Brazil'),
(31, 'IO', 'British Indian Ocean Territory'),
(32, 'BN', 'Brunei'),
(33, 'BG', 'Bulgaria'),
(34, 'BF', 'Burkina Faso'),
(35, 'BI', 'Burundi'),
(36, 'KH', 'Cambodia'),
(37, 'CM', 'Cameroon'),
(38, 'CA', 'Canada'),
(39, 'CV', 'Cape Verde'),
(40, 'KY', 'Cayman Islands'),
(41, 'CF', 'Central African Republic'),
(42, 'TD', 'Chad'),
(43, 'CL', 'Chile'),
(44, 'CN', 'China'),
(45, 'CX', 'Christmas Island'),
(46, 'CC', 'Cocos (Keeling) Islands'),
(47, 'CO', 'Colombia'),
(48, 'KM', 'Comoros'),
(49, 'CG', 'Congo'),
(50, 'ZR', 'Congo (The Democratic Republic Of The)'),
(51, 'CK', 'Cook Islands'),
(52, 'CR', 'Costa Rica'),
(53, 'CI', 'Cote D''Ivoire'),
(54, 'HR', 'Croatia'),
(55, 'CY', 'Cyprus'),
(56, 'CZ', 'Czech Republic'),
(57, 'DK', 'Denmark'),
(58, 'DJ', 'Djibouti'),
(59, 'DM', 'Dominica'),
(60, 'DO', 'Dominican Republic'),
(61, 'TP', 'East Timor'),
(62, 'EC', 'Ecuador'),
(63, 'EG', 'Egypt'),
(64, 'SV', 'El Salvador'),
(65, 'GQ', 'Equatorial Guinea'),
(66, 'ER', 'Eritrea'),
(67, 'EE', 'Estonia'),
(68, 'ET', 'Ethiopia'),
(69, 'FK', 'Falkland Islands'),
(70, 'FO', 'Faroe Islands'),
(71, 'FJ', 'Fiji'),
(72, 'FI', 'Finland'),
(73, 'FR', 'France'),
(74, 'FX', 'France Metropolitan'),
(75, 'GF', 'French Guiana'),
(76, 'PF', 'French Polynesia'),
(77, 'TF', 'French Southern Territories'),
(78, 'GA', 'Gabon'),
(79, 'GM', 'Gambia'),
(80, 'GE', 'Georgia'),
(81, 'DE', 'Germany'),
(82, 'GH', 'Ghana'),
(83, 'GI', 'Gibraltar'),
(84, 'GR', 'Greece'),
(85, 'GL', 'Greenland'),
(86, 'GD', 'Grenada'),
(87, 'GP', 'Guadeloupe'),
(88, 'GU', 'Guam'),
(89, 'GT', 'Guatemala'),
(90, 'GN', 'Guinea'),
(91, 'GW', 'Guinea-Bissau'),
(92, 'GY', 'Guyana'),
(93, 'HT', 'Haiti'),
(94, 'HM', 'Heard And Mc Donald Islands'),
(95, 'HN', 'Honduras'),
(96, 'HK', 'Hong Kong'),
(97, 'HU', 'Hungary'),
(98, 'IS', 'Iceland'),
(99, 'IN', 'India'),
(100, 'ID', 'Indonesia'),
(101, 'IE', 'Ireland'),
(102, 'IL', 'Israel'),
(103, 'IT', 'Italy'),
(104, 'JM', 'Jamaica'),
(105, 'JP', 'Japan'),
(106, 'JO', 'Jordan'),
(107, 'KZ', 'Kazakhstan'),
(108, 'KE', 'Kenya'),
(109, 'KI', 'Kiribati'),
(110, 'KW', 'Kuwait'),
(111, 'KG', 'Kyrgyzstan'),
(112, 'LA', 'Laos'),
(113, 'LV', 'Latvia'),
(114, 'LB', 'Lebanon'),
(115, 'LS', 'Lesotho'),
(116, 'LR', 'Liberia'),
(117, 'LI', 'Liechtenstein'),
(118, 'LT', 'Lithuania'),
(119, 'LU', 'Luxembourg'),
(120, 'MO', 'Macau'),
(121, 'MK', 'Macedonia (The F.Y.R. Of)'),
(122, 'MG', 'Madagascar'),
(123, 'MW', 'Malawi'),
(124, 'MY', 'Malaysia'),
(125, 'MV', 'Maldives'),
(126, 'ML', 'Mali'),
(127, 'MT', 'Malta'),
(128, 'MH', 'Marshall Islands'),
(129, 'MQ', 'Martinique'),
(130, 'MR', 'Mauritania'),
(131, 'MU', 'Mauritius'),
(132, 'YT', 'Mayotte'),
(133, 'MX', 'Mexico'),
(134, 'FM', 'Micronesia'),
(135, 'MD', 'Moldova'),
(136, 'MC', 'Monaco'),
(137, 'MN', 'Mongolia'),
(138, 'MS', 'Montserrat'),
(139, 'MA', 'Morocco'),
(140, 'MZ', 'Mozambique'),
(141, 'MM', 'Myanmar'),
(142, 'NA', 'Namibia'),
(143, 'NR', 'Nauru'),
(144, 'NP', 'Nepal'),
(145, 'NL', 'Netherlands'),
(146, 'AN', 'Netherlands Antilles'),
(147, 'NC', 'New Caledonia'),
(148, 'NZ', 'New Zealand'),
(149, 'NI', 'Nicaragua'),
(150, 'NE', 'Niger'),
(151, 'NG', 'Nigeria'),
(152, 'NU', 'Niue'),
(153, 'NF', 'Norfolk Island'),
(154, 'MP', 'Northern Mariana Islands'),
(155, 'NO', 'Norway'),
(156, 'OM', 'Oman'),
(157, 'PK', 'Pakistan'),
(158, 'PW', 'Palau'),
(159, 'PA', 'Panama'),
(160, 'PG', 'Papua New Guinea'),
(161, 'PY', 'Paraguay'),
(162, 'PE', 'Peru'),
(163, 'PH', 'Philippines'),
(164, 'PN', 'Pitcairn'),
(165, 'PL', 'Poland'),
(166, 'PT', 'Portugal'),
(167, 'PR', 'Puerto Rico'),
(168, 'QA', 'Qatar'),
(169, 'RE', 'Reunion'),
(170, 'RO', 'Romania'),
(171, 'RU', 'Russian Federation'),
(172, 'RW', 'Rwanda'),
(173, 'GS', 'S Georgia & S Sandwich Islands'),
(174, 'KN', 'Saint Kitts And Nevis'),
(175, 'LC', 'Saint Lucia'),
(176, 'VC', 'Saint Vincent & The Grenadines'),
(177, 'WS', 'Samoa'),
(178, 'SM', 'San Marino'),
(179, 'ST', 'Sao Tome And Principe'),
(180, 'SA', 'Saudi Arabia'),
(181, 'SN', 'Senegal'),
(182, 'YU', 'Serbia And Montenegro'),
(183, 'SC', 'Seychelles'),
(184, 'SL', 'Sierra Leone'),
(185, 'SG', 'Singapore'),
(186, 'SK', 'Slovakia'),
(187, 'SI', 'Slovenia'),
(188, 'SB', 'Solomon Islands'),
(189, 'SO', 'Somalia'),
(190, 'ZA', 'South Africa'),
(191, 'KR', 'South Korea'),
(192, 'ES', 'Spain'),
(193, 'LK', 'Sri Lanka'),
(194, 'SH', 'St. Helena'),
(195, 'PM', 'St. Pierre And Miquelon'),
(196, 'SR', 'Suriname'),
(197, 'SJ', 'Svalbard And Jan Mayen Islands'),
(198, 'SZ', 'Swaziland'),
(199, 'SE', 'Sweden'),
(200, 'CH', 'Switzerland'),
(201, 'TW', 'Taiwan'),
(202, 'TJ', 'Tajikistan'),
(203, 'TZ', 'Tanzania'),
(204, 'TH', 'Thailand'),
(205, 'TG', 'Togo'),
(206, 'TK', 'Tokelau'),
(207, 'TO', 'Tonga'),
(208, 'TT', 'Trinidad And Tobago'),
(209, 'TN', 'Tunisia'),
(210, 'TR', 'Turkey'),
(211, 'TM', 'Turkmenistan'),
(212, 'TC', 'Turks And Caicos Islands'),
(213, 'TV', 'Tuvalu'),
(214, 'UG', 'Uganda'),
(215, 'UA', 'Ukraine'),
(216, 'AE', 'United Arab Emirates'),
(217, 'GB', 'United Kingdom'),
(218, 'US', 'United States'),
(219, 'UM', 'United States Outlying Islands'),
(220, 'UY', 'Uruguay'),
(221, 'UZ', 'Uzbekistan'),
(222, 'VU', 'Vanuatu'),
(223, 'VA', 'Vatican City State'),
(224, 'VE', 'Venezuela'),
(225, 'VN', 'Vietnam'),
(226, 'VG', 'Virgin Islands (British)'),
(227, 'VI', 'Virgin Islands (U.S.)'),
(228, 'WF', 'Wallis And Futuna Islands'),
(229, 'EH', 'Western Sahara'),
(230, 'YE', 'Yemen'),
(231, 'ZM', 'Zambia'),
(232, 'ZW', 'Zimbabwe');
