INSERT INTO `research_areas` (`id`, `name`) VALUES
(1, 'Key Area 1 (Planetary aurorae, planetary radio emissions, planetary space weather)'),
(2, 'Key Area 2 (Small solar system objects: Astrometry, spectroscopy, stellar occultations, meteoroid impact effects)'),
(3, 'Key Area 3 (Airless bodies in the solar system: Moon, Mercury, Galilean satellites)'),
(4, 'Atmospheric Physics'),
(5, 'Supernovae / Novae'),
(6, 'Galaxies'),
(7, 'Interstellar Medium'),
(8, 'Exoplanets'),
(9, 'Stellar Physics'),
(10, 'Large Scale Structures'),
(11, 'Solar Physics'),
(12, 'Geodesy'),
(13, 'Cosmology'),
(14, 'Stellar Occultations'),
(15, 'Public Outreach / Education etc.'),
(16, 'Particle Physics'),
(17, 'Black Holes'),
(18, 'Astrobiology'),
(19, 'Astrochemistry'),
(20, 'Neutron Stars / Pulsars etc.'),
(21, 'Orbital Mechanics'),
(22, 'Interplanetary Medium'),
(23, 'Magnetospheric Physics'),
(24, 'Planetary Science');
