INSERT INTO `research_areas` (`id`, `domain`, `name`) VALUES
(4, 'ATMOSPHERIC PHYSICS', 'ATMOSPHERIC PHYSICS'),
(9, 'STELLAR PHYSICS', 'STELLAR PHYSICS'),
(11, 'SPACE PHYSICS', 'Solar Physics'),
(12, 'GEODESY', 'GEODESY'),
(13, 'COSMOLOGY', 'COSMOLOGY'),
(14, 'OBSERVATIONAL ASTROPHYSICS', 'Stellar Occultations'),
(15, 'PUBLIC OUTREACH / EDUCATION ETC.', 'PUBLIC OUTREACH / EDUCATION ETC.'),
(16, 'ASTROPARTICLE PHYSICS', 'ASTROPARTICLE PHYSICS'),
(18, 'ASTROBIOLOGY', 'ASTROBIOLOGY'),
(19, 'ASTROCHEMISTRY', 'ASTROCHEMISTRY'),
(20, 'STELLAR PHYSICS', 'Physics of White Dwarfs, Neutron Stars etc.'),
(21, 'CELESTIAL MECHANICS', 'Orbital Mechanics'),
(23, 'SPACE PHYSICS', 'Magnetospheric Physics'),
(25, 'ATMOSPHERIC PHYSICS', 'Climatology'),
(27, 'OBSERVATIONAL ASTROPHYSICS', 'Radio Astronomy'),
(28, 'OBSERVATIONAL ASTROPHYSICS', 'Astronomical Survey'),
(29, 'ATMOSPHERIC PHYSICS', 'Synoptic Meteorology'),
(31, 'OBSERVATIONAL ASTROPHYSICS', 'Optical Astronomy'),
(32, 'OBSERVATIONAL ASTROPHYSICS', 'Infrared Astronomy'),
(33, 'COSMOLOGY', 'Cosmic Microwave Background'),
(35, 'SPACE PHYSICS', 'Plasma Physics'),
(37, 'SPACE PHYSICS', 'Space Weather'),
(40, 'ASTROPARTICLE PHYSICS', 'High-Energy, VHE & UHE Gamma Ray Astronomy'),
(43, 'COSMOLOGY', 'The Observable Universe'),
(45, 'COSMOLOGY', 'Cosmogony, Big Bang & Early Universe'),
(48, 'COSMOLOGY', 'Exotic Matter, Dark Matter & Energy'),
(54, 'STELLAR PHYSICS', 'Star Formation'),
(58, 'ASTROCHEMISTRY', 'Chemical Evolution'),
(60, 'PLANETARY SCIENCES', 'Planetary Geology'),
(63, 'ASTROCHEMISTRY', 'Geochemistry'),
(65, 'STELLAR PHYSICS', 'Stellar Structure'),
(67, 'INSTRUMENTATION', 'INSTRUMENTATION'),
(71, 'PLANETARY SCIENCES', 'PLANETARY SCIENCES'),
(72, 'ASTROBIOLOGY', 'Abiogenesis (Astrobiology)'),
(73, 'ASTROBIOLOGY', 'Biomarkers'),
(74, 'ASTROBIOLOGY', 'Evolution of Life & Biodiversity'),
(75, 'ASTROBIOLOGY', 'Exoplanetary Research (Astrobiology)'),
(76, 'ASTROBIOLOGY', 'Life in the Solar System'),
(77, 'ASTROBIOLOGY', 'Planetary Habitability'),
(78, 'ASTROBIOLOGY', 'SETI - Search for Extra-Terrestrial Intelligence'),
(79, 'ASTROBIOLOGY', 'Stellar, Planetary & Atmospheric Evolution'),
(80, 'ASTROCHEMISTRY', 'Abiogenesis (Astrochemistry)'),
(81, 'ASTROCHEMISTRY', 'Atomic & Molecular Astrophysics'),
(82, 'ASTROCHEMISTRY', 'Cosmochemistry'),
(83, 'ASTROCHEMISTRY', 'Nucleocosmochronology'),
(84, 'ASTROPARTICLE PHYSICS', 'Cosmic Ray Physics (Astroparticle Physics)'),
(85, 'ASTROPARTICLE PHYSICS', 'Neutrino Astronomy (Astroparticle Physics)'),
(86, 'ASTROPARTICLE PHYSICS', 'Particle Physics  in Cosmology (Astroparticle Physics)'),
(87, 'ASTROPARTICLE PHYSICS', 'Related Astrophysics - Supernovae, AGN etc.'),
(88, 'ATMOSPHERIC PHYSICS', 'Aeronomy'),
(89, 'ATMOSPHERIC PHYSICS', 'Atmospheric Dynamics & Circulation'),
(90, 'ATMOSPHERIC PHYSICS', 'Atmospheric Energetics'),
(91, 'ATMOSPHERIC PHYSICS', 'Physical & Chemical Processes in the Atmosphere'),
(92, 'ATMOSPHERIC PHYSICS', 'Weather Forecasting'),
(93, 'ATMOSPHERIC PHYSICS', 'Weather Systems'),
(94, 'CELESTIAL MECHANICS', 'Astrometry'),
(95, 'CELESTIAL MECHANICS', 'CELESTIAL MECHANICS'),
(96, 'CELESTIAL MECHANICS', 'Celestial Navigation'),
(97, 'CELESTIAL MECHANICS', 'Ephemerides'),
(98, 'CELESTIAL MECHANICS', 'Lunar Theory'),
(99, 'COSMOLOGY', 'Gravitational Physics'),
(100, 'COSMOLOGY', 'Non-Standard Cosmology'),
(101, 'COSMOLOGY', 'Particle Physics in Cosmology'),
(102, 'COSMOLOGY', 'Structure Formation'),
(103, 'COSMOLOGY', 'Ultimate Fate of the Universe'),
(104, 'GEODESY', 'Cartography'),
(105, 'GEODESY', 'Geodetic Astronomy'),
(106, 'GEODESY', 'Photogrammetry'),
(107, 'GEODESY', 'Physical Geodesy'),
(108, 'GEODESY', 'Surveying'),
(109, 'OBSERVATIONAL ASTROPHYSICS', 'Earth Monitoring'),
(110, 'OBSERVATIONAL ASTROPHYSICS', 'Gamma Ray Astronomy'),
(111, 'OBSERVATIONAL ASTROPHYSICS', 'Gravitational Wave Astronomy'),
(112, 'OBSERVATIONAL ASTROPHYSICS', 'Neutrino Astronomy (Observational Astrophysics)'),
(113, 'OBSERVATIONAL ASTROPHYSICS', 'OBSERVATIONAL ASTROPHYSICS'),
(114, 'OBSERVATIONAL ASTROPHYSICS', 'Spectroscopy'),
(115, 'OBSERVATIONAL ASTROPHYSICS', 'UV Astronomy'),
(116, 'OBSERVATIONAL ASTROPHYSICS', 'X-Ray Astronomy'),
(117, 'PLANETARY SCIENCES', 'Exoplanetary Research (Planetary Sciences)'),
(118, 'PLANETARY SCIENCES', 'Geomorphology'),
(119, 'PLANETARY SCIENCES', 'Planetary Astronomy'),
(120, 'PLANETARY SCIENCES', 'Theoretical Planetology'),
(121, 'SPACE PHYSICS', 'Cosmic Ray Physics (Space Physics)'),
(122, 'SPACE PHYSICS', 'Heliospheric, Solar & Planetary Radio Emissions'),
(123, 'SPACE PHYSICS', 'Physics of Shockwaves'),
(124, 'SPACE PHYSICS', 'Planetary Aurorae'),
(125, 'SPACE PHYSICS', 'SPACE PHYSICS'),
(126, 'SPACE PHYSICS', 'Synchrotron Radiation'),
(127, 'STELLAR PHYSICS', 'Accretion Disks'),
(128, 'STELLAR PHYSICS', 'Asteroseismology'),
(129, 'STELLAR PHYSICS', 'Plasma Physics (Stellar Physics)'),
(130, 'STELLAR PHYSICS', 'Stellar Evolution');
