INSERT INTO `targets` (`id`, `target_name`) VALUES
(1, 'Venus'),
(2, 'Earth'),
(3, 'Mars'),
(4, 'Jupiter'),
(5, 'Saturn'),
(6, 'Uranus'),
(7, 'Neptune'),
(9, 'Moon'),
(31, 'Comets'),
(33, 'Asteroids'),
(34, 'Meteors'),
(36, 'TNOs (Trans-Neptunian Objects)'),
(45, 'Sun'),
(47, 'Exoplanets'),
(48, 'Planetary Satellites'),
(53, 'Mercury'),
(54, 'Artifical Satellites'),
(79, 'Interplanetary Medium'),
(146, 'Minor Planets'),
(218, 'All Targets');