INSERT INTO `targets` (`id`, `target_family`, `target_name`) VALUES
(1, 'PLANETS', 'Venus'),
(2, 'PLANETS', 'Earth'),
(3, 'PLANETS', 'Mars'),
(4, 'PLANETS', 'Jupiter'),
(5, 'PLANETS', 'Saturn'),
(6, 'PLANETS', 'Uranus'),
(7, 'PLANETS', 'Neptune'),
(8, 'PLANETS', 'Pluto'),
(9, 'PLANETS/Earth', 'Moon'),
(10, 'PLANETS/Mars', 'Phobos'),
(11, 'PLANETS/Mars', 'Deimos'),
(12, 'PLANETS/Jupiter', 'Jupiter Satellites'),
(13, 'PLANETS/Jupiter', 'Io'),
(14, 'PLANETS/Jupiter', 'Ganymede'),
(15, 'PLANETS/Jupiter', 'Callisto'),
(16, 'PLANETS/Saturn', 'Janus'),
(17, 'PLANETS/Saturn', 'Mimas'),
(18, 'PLANETS/Saturn', 'Enceladus'),
(19, 'PLANETS/Saturn', 'Tethys'),
(20, 'PLANETS/Saturn', 'Dione'),
(21, 'PLANETS/Saturn', 'Rhea'),
(22, 'PLANETS/Saturn', 'Titan'),
(23, 'PLANETS/Saturn', 'Hyperion'),
(24, 'PLANETS/Saturn', 'Iapetus'),
(25, 'PLANETS/Saturn', 'Phoebe'),
(26, 'PLANETS/Uranus', 'Uranus Satellites'),
(27, 'PLANETS/Neptune', 'Neptune Satellites'),
(28, 'PLANETS/Neptune', 'Nereid'),
(29, 'PLANETS/Pluto', 'Pluto Satellites'),
(30, 'PLANETS/Pluto', 'Charon'),
(31, 'SMALL BODIES', 'Comets'),
(32, 'SMALL BODIES', 'Kuiper Belt and Oort Cloud'),
(33, 'SMALL BODIES', 'Asteroids'),
(34, 'SMALL BODIES', 'Meteors'),
(35, 'PLANETS/Mars', 'Mars Satellites'),
(36, 'SMALL BODIES', 'TNO (Trans-Neptunian Objects)'),
(37, 'SMALL BODIES', 'SMALL BODIES'),
(38, 'PLANETS', 'RINGS'),
(39, 'PLANETS/Saturn', 'Saturn Rings'),
(40, 'PLANETS/Jupiter', 'Jupiter Rings'),
(41, 'PLANETS/Uranus', 'Uranus Rings'),
(42, 'PLANETS/Neptune', 'Neptune Rings'),
(43, 'SMALL BODIES/Asteroids', 'Vesta'),
(44, 'SMALL BODIES/Asteroids', 'Ceres'),
(45, 'SUN', 'SUN'),
(46, 'DUST', 'DUST'),
(47, 'EXOPLANETS', 'EXOPLANETS'),
(48, 'PLANETS', 'SATELLITES'),
(49, 'PLANETS/Jupiter', 'Europa'),
(50, 'PLANETS', 'PLANETS'),
(51, 'SMALL BODIES', 'Meteorites'),
(52, 'PLANETS/Saturn', 'Saturn Satellites'),
(53, 'PLANETS', 'Mercury');