INSERT INTO `telescope_types` (`id`, `name`) VALUES
(1, 'Newton'),
(2, 'Cassegrain'),
(3, 'Schmidt-Cassegrain'),
(4, 'Maksutov'),
(5, 'Ritchey-Chretien'),
(6, 'Dobson'),
(7, 'Refracting Telescope'),
(8, 'Binocular Telescope'),
(10, 'Radio Telescope'),
(11, 'Underground Telescope'),
(13, 'Magnetometer'),
(14, 'Riometer'),
(15, 'Other'), /** needs to be removed in final version */
(16, 'Newton-Cassegrain'),
(17, 'Reflecting Telescope'),
(18, 'Schmidt'),
(19, 'Gregorian Telescope'),
(20, 'Solar Telescope'),
(21, 'Corrected Dall-Kirkham Astrograph'),
(22, 'Apochromatic refractor'),
(23, 'ACF Optics'),
(24, 'Cassegrain-Nasmyth');