INSERT INTO `telescope_types` (`id`, `name`) VALUES
(1, 'Newton'),
(2, 'Cassegrain'),
(3, 'Schmidt-Cassegrain'),
(4, 'Maksutov'),
(5, 'Ritchey-Chretien'),
(6, 'Dobson'),
(7, 'Refracting Telescope'),
(8, 'Binocular Telescope'),
(9, 'Spectrometer'),
(10, 'Radio Telescope'),
(11, 'Underground Telescope'),
(12, 'Interferometer'),
(13, 'Magnetometer'),
(14, 'Riometer'),
(15, 'Other'),
(16, 'Newton-Cassegrain'),
(17, 'Reflecting Telescope'),
(18, 'Schmidt'),
(19, 'Gregorian Telescope');
